import { z } from "zod";
import { QUESTIONNAIRE } from "@/lib/questionnaire-config";

// Structured shape the model must return (and the shape we store/render).
export const riskSummarySchema = z.object({
  summary: z
    .string()
    .describe("A 3-5 sentence executive risk summary for a security buyer."),
  topRisks: z
    .array(z.string())
    .describe("The top 3 concrete risks, most severe first."),
  gaps: z
    .array(z.string())
    .describe("Specific missing controls or unanswered concerns."),
  tier: z
    .enum(["LOW", "MEDIUM", "HIGH", "CRITICAL"])
    .describe("Overall risk tier for this vendor."),
});

export type RiskSummaryResult = z.infer<typeof riskSummarySchema>;

/** Render questionnaire answers into a human-readable block for the prompt. */
function renderAnswers(answers: Record<string, unknown>): string {
  const lines: string[] = [];
  for (const section of QUESTIONNAIRE) {
    lines.push(`\n## ${section.title}`);
    for (const f of section.fields) {
      const v = answers[f.id];
      const shown =
        v === undefined || v === null || v === ""
          ? "(no answer)"
          : typeof v === "boolean"
            ? v
              ? "Yes"
              : "No"
            : String(v);
      lines.push(`- ${f.label}: ${shown}`);
    }
  }
  return lines.join("\n");
}

export function buildPrompt(
  vendorName: string,
  answers: Record<string, unknown>
): string {
  return `You are a third-party cyber-risk analyst. Assess the vendor "${vendorName}" based on their security questionnaire responses below.

Produce:
1. A concise executive summary (3-5 sentences).
2. The top 3 concrete risks, most severe first.
3. Specific gaps — missing controls, weak answers, or unanswered questions.
4. An overall risk tier: LOW, MEDIUM, HIGH, or CRITICAL.

Weigh heavily: lack of MFA, no encryption at rest, no incident response plan, customer data sent to AI models unprotected, and missing certifications. Be specific and reference the vendor's actual answers.

Questionnaire responses:
${renderAnswers(answers)}`;
}

/**
 * Deterministic fallback used when OPENAI_API_KEY is not configured, so the
 * whole flow is testable locally without spending tokens. Heuristics mirror the
 * factors the prompt tells the model to weigh.
 */
export function stubSummary(
  vendorName: string,
  answers: Record<string, unknown>
): RiskSummaryResult {
  const gaps: string[] = [];
  const risks: string[] = [];
  let score = 0;

  const mfa = String(answers["mfa_enforced"] ?? "");
  if (mfa !== "Yes") {
    gaps.push("MFA is not fully enforced across the organization.");
    risks.push("Account takeover risk from missing multi-factor authentication.");
    score += mfa === "No" ? 2 : 1;
  }
  if (String(answers["encryption_at_rest"] ?? "") !== "Yes") {
    gaps.push("Data is not encrypted at rest.");
    risks.push("Exposure of stored data in the event of a breach.");
    score += 2;
  }
  if (String(answers["incident_response"] ?? "") !== "Yes") {
    gaps.push("No documented incident response plan.");
    risks.push("Slow, uncoordinated response to security incidents.");
    score += 1;
  }
  if (String(answers["customer_data_in_ai"] ?? "") === "Yes") {
    gaps.push("Customer data is sent to AI models without anonymization.");
    risks.push("Sensitive data leakage through third-party AI providers.");
    score += 2;
  }
  const certs = String(answers["certifications"] ?? "");
  if (certs === "None" || certs === "") {
    gaps.push("No recognized security certifications (SOC 2 / ISO 27001).");
    score += 1;
  }

  const tier =
    score >= 5 ? "CRITICAL" : score >= 3 ? "HIGH" : score >= 1 ? "MEDIUM" : "LOW";

  const summary = `Automated assessment of ${vendorName} based on questionnaire responses. ${
    gaps.length
      ? `Identified ${gaps.length} control gap(s) affecting the overall posture.`
      : "No significant control gaps were identified."
  } The vendor is rated ${tier} risk. (Generated by the local dev stub — set OPENAI_API_KEY for an AI-authored summary.)`;

  return {
    summary,
    topRisks: risks.slice(0, 3).length
      ? risks.slice(0, 3)
      : ["No major risks identified from the provided answers."],
    gaps: gaps.length ? gaps : ["No material gaps identified."],
    tier,
  };
}

/**
 * Generate a risk summary. Uses OpenAI when configured, otherwise the stub.
 * Kept provider-agnostic behind this single entry point.
 */
export async function generateRiskSummary(
  vendorName: string,
  answers: Record<string, unknown>
): Promise<{ result: RiskSummaryResult; source: "openai" | "stub" }> {
  if (!process.env.OPENAI_API_KEY) {
    return { result: stubSummary(vendorName, answers), source: "stub" };
  }

  // Imported lazily so the dependency is only loaded when a key is present.
  const { generateObject } = await import("ai");
  const { openai } = await import("@ai-sdk/openai");

  const { object } = await generateObject({
    model: openai(process.env.OPENAI_MODEL ?? "gpt-4o-mini"),
    schema: riskSummarySchema,
    prompt: buildPrompt(vendorName, answers),
  });

  return { result: object, source: "openai" };
}
